server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: homelab

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: http://socket-proxy:2375
        refresh_interval: 5s
        filters:
          - name: label
            values:
              - monitoring=true
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: /(.*)
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
    pipeline_stages:
      - json:
          expressions:
            level: level
            event: event
            request_id: request_id
            job_id: job_id
      - labels:
          level:
          service:
          project:
