apiVersion: 1
contactPoints:
  - orgId: 1
    name: homelab-webhook
    receivers:
      - uid: homelab-webhook
        type: webhook
        settings:
          url: $ALERTING_WEBHOOK_URL
          httpMethod: POST
